### PR TITLE
fixed cursor bug in deployment

### PR DESCRIPTION
**Pull request by pgm-sybrdebo**

### CODE REVIEW

**Review by BT-Creator — APPROVED** [review]
LGTM! For the `package.json`, no dependencies changes were detected.

**Review by juliavdkris — CHANGES_REQUESTED** [review]
What's up with the package-lock.json? 38.000 deletions :panik:

**Comment by juliavdkris** [comment]
Ah nevermind, I see npm 6.x on the Node 14 image is complaining when using version 2 lockfiles, so I'm guessing that was why?

**Review by juliavdkris — APPROVED** [review]

**Comment by LieselotGeirnaert** [comment]
👍

**Review by LieselotGeirnaert — APPROVED** [review]

**Pull request merged**
